services:
  db:
    image: postgres:14-alpine
    container_name: database-portal-rh
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 122400
      POSTGRES_DB: portaldb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: